### 1. 라이브러리 불러오기
* request = API 서버에 요청
* pandas = 데이터를 표로 정리(DataFrame)

In [1]:
import requests
import pandas as pd

### 2. 인증 키 설정

In [2]:
client_id = "Nkzrmabq5_CCZFxwmylU"
client_secret = "b8snvM9GKl"

### 3. 함수 정의
* query = 검색어
* display = 기사 개수
* start = 시작 위치

1) API url 설정 (요청 대상)
2) 헤더 설정 (인증)
3) 파라미터 설정 (가독성)
4) API 요청
* response = requests.get(url, headers=headers, params=params)

### 1) 뉴스 데이터 수집

In [36]:
def search_news(query, display=100, start=1):
    url = "https://openapi.naver.com/v1/search/news.json"
    headers = {"X-Naver-Client-Id": client_id,
        "X-Naver-Client-Secret": client_secret}
    params = {"query": query,
                "display": display,
                "start": start,
                "sort": "date"}
    response = requests.get(url, headers=headers, params=params)
    return response.json()

data = search_news("핀테크")

### 2) 페이지네이션: 여러 페이지에서 가져온 데이터를 하나로 모음

In [37]:
all_news = []

for start in range(1, 1000, 100):
    data = search_news("핀테크", start=start)

    for item in data["items"]:
        all_news.append(item)
        
print(len(all_news))

1000

In [59]:
df = pd.DataFrame(all_news)
df

,title,originallink,link,description,pubDate
0,"토스, 디자인스쿨 열고 직접 인재 키운다…'한국형 애플' 전략",https://www.newspim.com/news/view/20260325001015,https://www.newspim.com/news/view/20260325001015,토스는 직관적인 UI·UX(사용자환경·경험)를 핵심 경쟁력으로 빠르게 성장한 대표 ...,"Wed, 25 Mar 2026 15:17:00 +0900"
1,"신한투자증권, '행복이음신탁' 강화 위해 세무법인과 MOU",http://www.whitepaper.co.kr/news/articleView.h...,http://www.whitepaper.co.kr/news/articleView.h...,"가상자산, <b>핀테크</b>, 유언대용신탁 등 신규 금융 부문에 선제적으로 진출하...","Wed, 25 Mar 2026 15:14:00 +0900"
2,‘서울시장 도전’ 민주 박주민 “서울투자공사 설립...세계의 돈과 인...,https://www.mk.co.kr/article/11998004,https://n.news.naver.com/mnews/article/009/000...,박 의원은 서울투자공사를 통해 인공지능(AI)·바이오·<b>핀테크</b> 등 전략 ...,"Wed, 25 Mar 2026 15:10:00 +0900"
3,신한證·세무법인 디엘지 '행복이음신탁' 강화 MOU,http://www.smedaily.co.kr/news/articleView.htm...,http://www.smedaily.co.kr/news/articleView.htm...,"가상자산, <b>핀테크</b>, 유언대용신탁 등 신규 금융 부문에 선제적으로 진출해...","Wed, 25 Mar 2026 15:04:00 +0900"
4,"신한투자증권, 세무법인 디엘지와 행복이음신탁 업무협약",http://www.bizwnews.com/news/articleView.html?...,http://www.bizwnews.com/news/articleView.html?...,세무법인 디엘지는 국세청·대형 회계법인 출신 세무사들로 구성됐으며 가상자산·<b>핀...,"Wed, 25 Mar 2026 15:00:00 +0900"
...,...,...,...,...,...
995,"설마했는데…“아무도 이럴 줄 몰랐다” 국민 포털 ‘특단의 조치’, 무...",https://biz.heraldcorp.com/article/10695431?re...,https://n.news.naver.com/mnews/article/016/000...,아울러 <b>핀테크</b>·플랫폼 회사 7곳을 흡수했다. 세부적으로 ▷아실 ▷퍼플덕...,"Mon, 16 Mar 2026 21:41:00 +0900"
996,"핑거, 보통주 1주당 100원 현금배당 결정",https://www.digitaltoday.co.kr/news/articleVie...,https://www.digitaltoday.co.kr/news/articleVie...,<b>핀테크</b> 전문 기업 핑거(163730)는 결산배당으로 보통주 1주당 10...,"Mon, 16 Mar 2026 18:56:00 +0900"
997,주총 여는 '네카오'… 키워드는 AI 고도화·책임경영,http://www.fnnews.com/news/202603161845006978,https://n.news.naver.com/mnews/article/014/000...,"네이버가 오는 6월을 목표로 네이버파이낸셜과 두나무 합병절차를 밟고 있는 만큼, 재...","Mon, 16 Mar 2026 18:46:00 +0900"
998,"쿠콘, 2025년 연간 실적 공시… 수익성 중심 경영으로 '내실 강화' 입증",http://www.intn.co.kr/news/articleView.html?id...,http://www.intn.co.kr/news/articleView.html?id...,이어 &quot;2026년은 신사업들이 본격적인 수익화 단계에 진입하는 도약의 해가...,"Mon, 16 Mar 2026 18:30:00 +0900"
999,"웹케시·로움아이티, 세무법인 아성과 전략적 제휴",http://www.intn.co.kr/news/articleView.html?id...,http://www.intn.co.kr/news/articleView.html?id...,"설립한 <b>핀테크</b> 전문 기업으로, 1999년 설립 이후 20여 년간 국내 ...","Mon, 16 Mar 2026 18:28:00 +0900"

### 3. 데이터 정제

In [68]:
import re

In [69]:
# 1. 컬럼 삭제
df = df.drop(columns=["originallink"])

# 2. HTML 태그 제거 함수 정의
def remove_html(text):
    return re.sub('<.*?>', '', text)

# 3. 함수 적용
df["title"] = df["title"].apply(remove_html)
df["description"] = df["description"].apply(remove_html)

# 4. 확인
df

,title,link,description,pubDate
0,"토스, 디자인스쿨 열고 직접 인재 키운다…'한국형 애플' 전략",https://www.newspim.com/news/view/20260325001015,토스는 직관적인 UI·UX(사용자환경·경험)를 핵심 경쟁력으로 빠르게 성장한 대표 ...,"Wed, 25 Mar 2026 15:17:00 +0900"
1,"신한투자증권, '행복이음신탁' 강화 위해 세무법인과 MOU",http://www.whitepaper.co.kr/news/articleView.h...,"가상자산, 핀테크, 유언대용신탁 등 신규 금융 부문에 선제적으로 진출하여 업계 최고...","Wed, 25 Mar 2026 15:14:00 +0900"
2,‘서울시장 도전’ 민주 박주민 “서울투자공사 설립...세계의 돈과 인...,https://n.news.naver.com/mnews/article/009/000...,박 의원은 서울투자공사를 통해 인공지능(AI)·바이오·핀테크 등 전략 산업에 서울시...,"Wed, 25 Mar 2026 15:10:00 +0900"
3,신한證·세무법인 디엘지 '행복이음신탁' 강화 MOU,http://www.smedaily.co.kr/news/articleView.htm...,"가상자산, 핀테크, 유언대용신탁 등 신규 금융 부문에 선제적으로 진출해 전문 세무 ...","Wed, 25 Mar 2026 15:04:00 +0900"
4,"신한투자증권, 세무법인 디엘지와 행복이음신탁 업무협약",http://www.bizwnews.com/news/articleView.html?...,세무법인 디엘지는 국세청·대형 회계법인 출신 세무사들로 구성됐으며 가상자산·핀테크·...,"Wed, 25 Mar 2026 15:00:00 +0900"
...,...,...,...,...
995,"설마했는데…“아무도 이럴 줄 몰랐다” 국민 포털 ‘특단의 조치’, 무...",https://n.news.naver.com/mnews/article/016/000...,아울러 핀테크·플랫폼 회사 7곳을 흡수했다. 세부적으로 ▷아실 ▷퍼플덕 ▷증권플러스...,"Mon, 16 Mar 2026 21:41:00 +0900"
996,"핑거, 보통주 1주당 100원 현금배당 결정",https://www.digitaltoday.co.kr/news/articleVie...,핀테크 전문 기업 핑거(163730)는 결산배당으로 보통주 1주당 100원 현금배당...,"Mon, 16 Mar 2026 18:56:00 +0900"
997,주총 여는 '네카오'… 키워드는 AI 고도화·책임경영,https://n.news.naver.com/mnews/article/014/000...,"네이버가 오는 6월을 목표로 네이버파이낸셜과 두나무 합병절차를 밟고 있는 만큼, 재...","Mon, 16 Mar 2026 18:46:00 +0900"
998,"쿠콘, 2025년 연간 실적 공시… 수익성 중심 경영으로 '내실 강화' 입증",http://www.intn.co.kr/news/articleView.html?id...,이어 &quot;2026년은 신사업들이 본격적인 수익화 단계에 진입하는 도약의 해가...,"Mon, 16 Mar 2026 18:30:00 +0900"
999,"웹케시·로움아이티, 세무법인 아성과 전략적 제휴",http://www.intn.co.kr/news/articleView.html?id...,"설립한 핀테크 전문 기업으로, 1999년 설립 이후 20여 년간 국내 최고 기술 및...","Mon, 16 Mar 2026 18:28:00 +0900"

In [67]:
df = pd.DataFrame(all_news)
df.to_csv("[연습문제] fintech_news.csv", index=False, encoding="utf-8-sig")