In [1]:
import pandas as pd

In [2]:
# dataframe
data = {'country': ['Belgium', 'France', 'Germany', 'Netherlands', 'United Kingdom'],
        'population': [11.3, 64.3, 81.3, 16.9, 64.9],
        'area': [30510, 671308, 357050, 41526, 244820],
        'capital': ['Brussels', 'Paris', 'Berlin', 'Amsterdam', 'London']}
countries = pd.DataFrame(data)
countries = countries.set_index('country') # 인덱스 지정
countries

                population    area    capital
country
Belgium               11.3   30510   Brussels
France                64.3  671308      Paris
Germany               81.3  357050     Berlin
Netherlands           16.9   41526  Amsterdam
United Kingdom        64.9  244820     London

In [3]:
countries.info()

<class 'pandas.DataFrame'>
Index: 5 entries, Belgium to United Kingdom
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   population  5 non-null      float64
 1   area        5 non-null      int64
 2   capital     5 non-null      str
dtypes: float64(1), int64(1), str(1)
memory usage: 160.0+ bytes

---

<div class="alert alert-success">
    <b>EXERCISE 01</b>: 인구밀도를 의미하는 `density` 칼럼을 추가하세요. (주의: 현재 'population' 칼럼은 100만 단위로 표기되어 있습니다)  
  
</div>

In [4]:
countries['density'] = (countries['population'] * 1000000) / countries['area']
countries

                population    area    capital     density
country
Belgium               11.3   30510   Brussels  370.370370
France                64.3  671308      Paris   95.783158
Germany               81.3  357050     Berlin  227.699202
Netherlands           16.9   41526  Amsterdam  406.973944
United Kingdom        64.9  244820     London  265.092721

<div class="alert alert-success">
    <b>EXERCISE 02</b>: 인구밀도가 300을 초과하는 국가(country)의 수도(capital)과 인구(population)을 선택해주세요.  
  
</div>

In [5]:
countries.loc[(countries["density"] > 300), ['capital', 'population']]
# 변수.loc[행 조건, 열 목록]
# 열 목록에 인덱스를 입력하지 않음

               capital  population
country
Belgium       Brussels        11.3
Netherlands  Amsterdam        16.9

<div class="alert alert-success">
    <b>EXERCISE 03</b>: 'density_ratio' 칼럼을 추가해주세요. (density_ratio = 인구밀도/평균 인구밀도)
</div>

In [6]:
countries['density_ratio'] = countries['density'] / countries['density'].mean()
countries
# 평균 함수 .mean()

                population    area    capital     density  density_ratio
country
Belgium               11.3   30510   Brussels  370.370370       1.355755
France                64.3  671308      Paris   95.783158       0.350618
Germany               81.3  357050     Berlin  227.699202       0.833502
Netherlands           16.9   41526  Amsterdam  406.973944       1.489744
United Kingdom        64.9  244820     London  265.092721       0.970382

<div class="alert alert-success">
    <b>EXERCISE 04</b>: 영국(United Kingdom)의 수도(capital)를 'Cambridge'로 변경해주세요.
</div>

In [7]:
countries.loc['United Kingdom', "capital"] = 'Cambridge'
countries
# countries = countries.drop(('United Kingdom', 'capital'), axis=1)

                population    area    capital     density  density_ratio
country
Belgium               11.3   30510   Brussels  370.370370       1.355755
France                64.3  671308      Paris   95.783158       0.350618
Germany               81.3  357050     Berlin  227.699202       0.833502
Netherlands           16.9   41526  Amsterdam  406.973944       1.489744
United Kingdom        64.9  244820  Cambridge  265.092721       0.970382

<div class="alert alert-success">
    <b>EXERCISE 05</b>: 인구 밀도가 100 초과, 300 미만인 국가들을 표시해주세요.  
</div>

In [8]:
countries.loc[(countries["density"] > 100) & (countries["density"] < 300)]

                population    area    capital     density  density_ratio
country
Germany               81.3  357050     Berlin  227.699202       0.833502
United Kingdom        64.9  244820  Cambridge  265.092721       0.970382

<div class="alert alert-success">
    <b>EXERCISE 06</b>: 수도가 7글자 이상인 국가들을 표시해주세요. (힌트: string의 len( )를 사용하세요.)
</div>

In [9]:
countries.loc[(countries["capital"].str.len() > 7)]

                population    area    capital     density  density_ratio
country
Belgium               11.3   30510   Brussels  370.370370       1.355755
Netherlands           16.9   41526  Amsterdam  406.973944       1.489744
United Kingdom        64.9  244820  Cambridge  265.092721       0.970382

<div class="alert alert-success">
    <b>EXERCISE 07</b>: 수도에 'am' 이 포함되는 국가들을 표시해주세요. (힌트: string의 contains( )를 사용하세요.)
</div>

In [10]:
countries.loc[countries["capital"].str.contains('am')]

                population    area    capital     density  density_ratio
country
Netherlands           16.9   41526  Amsterdam  406.973944       1.489744
United Kingdom        64.9  244820  Cambridge  265.092721       0.970382

# 영화리뷰 데이터에서 자료 찾기

movie_title_data.tsv 읽어오기

https://drive.google.com/file/d/1cvBtLVyfhfodJK-BXWqBLcopyus9HOIc/view?usp=sharing

In [11]:
titles = pd.read_csv('./data/movie_title_data.tsv', sep='\t')

df = pd.DataFrame(titles)
df

ParserError: Error tokenizing data. C error: Calling read(nbytes) on source failed. Try engine='python'.

In [ ]:
# print(type(titles[titles['startYear'].isna()]['startYear'][0]))

In [ ]:
# titles['startYear'] = titles['startYear'].astype("float16")
# titles['startYear']

<div class="alert alert-success">
    <b>EXERCISE 08</b>: titles 데이터프레임에는 몇 개의 영화가 기록되어 있나요?
</div>

In [ ]:
titles.shape[0]

<div class="alert alert-success">
    <b>EXERCISE 09</b>: titles에서 가장 빠른 시기에 제작된 영화 두 개를 표시하세요.  힌트: .sort_values()
</div>

In [ ]:
df['startYear'] = pd.to_numeric(df['startYear'], errors='coerce')
df.sort_values(by='startYear', ascending=True).head(2)

<div class="alert alert-success">
    <b>EXERCISE 10</b>: 제목(title)이 "Hamlet"인 영화는 몇 개가 있나요?
</div>

In [ ]:
len(df[(df['originalTitle'] == 'Hamlet') & (df['primaryTitle'] == 'Hamlet')])

<div class="alert alert-success">
    <b>EXERCISE 11</b>: 제목(title)이 "Treasure Island"인 영화를 제작년도(year)의 오름차순에 따라 표시하세요
</div>

In [ ]:
# 1. 필터링 제목(title)= "Treasure Island"
# 2. 필터링 제작년도(year)=오름차순

df[(df["originalTitle"] == "Treasure Island")].sort_values(by='startYear', ascending=True)

<div class="alert alert-success">
    <b>EXERCISE 12</b>: 1950년에서 1959년 사이 몇 개의 영화가 만들어졌나요?(1950 <= 제작년도 <= 1959)
</div>

In [ ]:
# 1. 1950-1959 영화조회
# 2. 개수

len(df[(df["startYear"] <= 1959) & (df["startYear"] >= 1950)])

# 타이타닉 자료에서 그룹별 연산하기

원격 DB에 접속해서 titanic 데이터베이스 안에 있는 p_info, t_info, survived 테이블을 불러와 합치고 아래의 문제를 풀어보세요.<br>
<id:kict00, pw:kict00, ip:221.155.18.165:3306, db:titanic>

In [12]:
import os
from sqlalchemy import create_engine
import pymysql
pymysql.install_as_MySQLdb()
from dotenv import load_dotenv
load_dotenv("../06 Marchine_learning_Deep_learning/.env")

True

In [13]:
dbid = os.getenv("id2")
dbpw = os.getenv("pw2")
host = os.getenv("ip2")
port = os.getenv("port2")
dbname = os.getenv("db2")

In [14]:
engine = create_engine(f"mysql+pymysql://{dbid}:{dbpw}@{host}:{port}/{dbname}")
conn = engine.connect()

In [16]:
table1 = pd.read_sql("p_info", con=conn)
table2 = pd.read_sql("t_info", con=conn)
table3 = pd.read_sql("survived", con=conn)

In [18]:
merged_table = pd.merge(table1, table2, how="inner", on = "PassengerId")
merged_table

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked
0,1,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,3,7.2500,NaN,S
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,1,71.2833,C85,C
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,3,7.9250,NaN,S
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,1,53.1000,C123,S
4,5,"Allen, Mr. William Henry",male,35.0,0,0,373450,3,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",male,27.0,0,0,211536,2,13.0000,NaN,S
887,888,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,1,30.0000,B42,S
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,3,23.4500,NaN,S
889,890,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,1,30.0000,C148,C
890,891,"Dooley, Mr. Patrick",male,32.0,0,0,370376,3,7.7500,NaN,Q

In [48]:
df = pd.merge(merged_table, table3, how="inner", on = "PassengerId")
df

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,3,7.2500,NaN,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,1,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,3,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,1,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",male,35.0,0,0,373450,3,8.0500,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",male,27.0,0,0,211536,2,13.0000,NaN,S,0
887,888,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,1,30.0000,B42,S,1
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,3,23.4500,NaN,S,0
889,890,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,1,30.0000,C148,C,1
890,891,"Dooley, Mr. Patrick",male,32.0,0,0,370376,3,7.7500,NaN,Q,0

<div class="alert alert-success">
    <b>EXERCISE 13</b>: 데이터의 상위 5개 행을 출력하세요.
</div>

In [56]:
df.head(5)

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,3,7.2500,NaN,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,1,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,3,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,1,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",male,35.0,0,0,373450,3,8.0500,NaN,S,0

<div class="alert alert-success">
    <b>EXERCISE 14</b>: 데이터의 정보(info)를 출력하세요.
</div>

In [57]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Name         891 non-null    str
 2   Sex          891 non-null    str
 3   Age          714 non-null    float64
 4   SibSp        891 non-null    int64
 5   Parch        891 non-null    int64
 6   Ticket       891 non-null    str
 7   Pclass       891 non-null    int64
 8   Fare         891 non-null    float64
 9   Cabin        204 non-null    str
 10  Embarked     889 non-null    str
 11  Survived     891 non-null    int64
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

<div class="alert alert-success">
    <b>EXERCISE 15</b>: 데이터의 기술통계(describe)를 확인하세요.
</div>

In [58]:
df.describe()

,PassengerId,Age,SibSp,Parch,Pclass,Fare,Survived
count,891.000000,714.000000,891.000000,891.000000,891.000000,891.000000,891.000000
mean,446.000000,29.699118,0.523008,0.381594,2.308642,32.204208,0.383838
std,257.353842,14.526497,1.102743,0.806057,0.836071,49.693429,0.486592
min,1.000000,0.420000,0.000000,0.000000,1.000000,0.000000,0.000000
25%,223.500000,20.125000,0.000000,0.000000,2.000000,7.910400,0.000000
50%,446.000000,28.000000,0.000000,0.000000,3.000000,14.454200,0.000000
75%,668.500000,38.000000,1.000000,0.000000,3.000000,31.000000,1.000000
max,891.000000,80.000000,8.000000,6.000000,3.000000,512.329200,1.000000

<div class="alert alert-success">
    <b>EXERCISE 16</b>: 처음 100명의 데이터를 출력하세요.
</div>

In [59]:
pd.set_option("display.max_rows", 100)
df

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,3,7.2500,NaN,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,1,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,3,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,1,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",male,35.0,0,0,373450,3,8.0500,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",male,27.0,0,0,211536,2,13.0000,NaN,S,0
887,888,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,1,30.0000,B42,S,1
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,3,23.4500,NaN,S,0
889,890,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,1,30.0000,C148,C,1
890,891,"Dooley, Mr. Patrick",male,32.0,0,0,370376,3,7.7500,NaN,Q,0

<div class="alert alert-success">
    <b>EXERCISE 17</b>: 인덱스가 10~20인 데이터를 출력하세요.
</div>

In [60]:
df.loc[10:20, :]

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
10,11,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,3,16.7000,G6,S,1
11,12,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,1,26.5500,C103,S,1
12,13,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,3,8.0500,NaN,S,0
13,14,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,3,31.2750,NaN,S,0
14,15,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,3,7.8542,NaN,S,0
15,16,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,2,16.0000,NaN,S,1
16,17,"Rice, Master. Eugene",male,2.0,4,1,382652,3,29.1250,NaN,Q,0
17,18,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,2,13.0000,NaN,S,1
18,19,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,3,18.0000,NaN,S,0
19,20,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,3,7.2250,NaN,C,1
20,21,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,2,26.0000,NaN,S,0

<div class="alert alert-success">
    <b>EXERCISE</b>: 컬럼 이름을 모두 출력하세요.
</div>

In [61]:
df.columns

Index(['PassengerId', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket',
       'Pclass', 'Fare', 'Cabin', 'Embarked', 'Survived'],
      dtype='str')

<div class="alert alert-success">
    <b>EXERCISE 18</b>: 데이터의 shape를 확인하세요.
</div>

In [62]:
df.shape

(891, 12)

<div class="alert alert-success">
    <b>EXERCISE 19</b>: 'Age' 컬럼의 평균을 구하세요.
</div>

In [63]:
df['Age'].mean()

np.float64(29.69911764705882)

<div class="alert alert-success">
    <b>EXERCISE 20</b>: 'Survived' 컬럼의 고유값을 확인하세요.
</div>

In [64]:
df['Survived'].unique()

array([0, 1])

<div class="alert alert-success">
    <b>EXERCISE 21</b>: 나이가 30 이상인 승객만 출력하세요.
</div>

In [65]:
df[df["Age"] >= 30]

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,1,71.2833,C85,C,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,1,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",male,35.0,0,0,373450,3,8.0500,NaN,S,0
6,7,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,1,51.8625,E46,S,0
11,12,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,1,26.5500,C103,S,1
...,...,...,...,...,...,...,...,...,...,...,...,...
873,874,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,3,9.0000,NaN,S,0
879,880,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,1,83.1583,C50,C,1
881,882,"Markun, Mr. Johann",male,33.0,0,0,349257,3,7.8958,NaN,S,0
885,886,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,3,29.1250,NaN,Q,0
890,891,"Dooley, Mr. Patrick",male,32.0,0,0,370376,3,7.7500,NaN,Q,0

<div class="alert alert-success">
    <b>EXERCISE 22</b>: 성별이 'female'이고 생존한 승객만 출력하세요.
</div>

In [66]:
df[(df['Sex'] == 'female') & (df['Survived'] == 1)]

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,1,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,3,7.9250,NaN,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,1,53.1000,C123,S,1
8,9,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,3,11.1333,NaN,S,1
9,10,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,2,30.0708,NaN,C,1
...,...,...,...,...,...,...,...,...,...,...,...,...
874,875,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,2,24.0000,NaN,C,1
875,876,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,3,7.2250,NaN,C,1
879,880,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,1,83.1583,C50,C,1
880,881,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,2,26.0000,NaN,S,1
887,888,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,1,30.0000,B42,S,1

<div class="alert alert-success">
    <b>EXERCISE 23</b>: 나이가 10살 이하이고 요금이 20 이상인 승객을 출력하세요.
</div>

In [67]:
df[(df['Age'] <= 10) & (df['Fare'] >= 20)]

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
7,8,"Palsson, Master. Gosta Leonard",male,2.00,3,1,349909,3,21.0750,NaN,S,0
16,17,"Rice, Master. Eugene",male,2.00,4,1,382652,3,29.1250,NaN,Q,0
24,25,"Palsson, Miss. Torborg Danira",female,8.00,3,1,349909,3,21.0750,NaN,S,0
43,44,"Laroche, Miss. Simonne Marie Anne Andree",female,3.00,1,2,SC/Paris 2123,2,41.5792,NaN,C,1
50,51,"Panula, Master. Juha Niilo",male,7.00,4,1,3101295,3,39.6875,NaN,S,0
58,59,"West, Miss. Constance Mirium",female,5.00,1,2,C.A. 34651,2,27.7500,NaN,S,1
63,64,"Skoog, Master. Harald",male,4.00,3,2,347088,3,27.9000,NaN,S,0
78,79,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,2,29.0000,NaN,S,1
119,120,"Andersson, Miss. Ellis Anna Maria",female,2.00,4,2,347082,3,31.2750,NaN,S,0
147,148,"Ford, Miss. Robina Maggie ""Ruby""",female,9.00,2,2,W./C. 6608,3,34.3750,NaN,S,0
164,165,"Panula, Master. Eino Viljami",male,1.00,4,1,3101295,3,39.6875,NaN,S,0
165,166,"Goldsmith, Master. Frank John William ""Frankie""",male,9.00,0,2,363291,3,20.5250,NaN,S,1
171,172,"Rice, Master. Arthur",male,4.00,4,1,382652,3,29.1250,NaN,Q,0
182,183,"Asplund, Master. Clarence Gustaf Hugo",male,9.00,4,2,347077,3,31.3875,NaN,S,0
183,184,"Becker, Master. Richard F",male,1.00,2,1,230136,2,39.0000,F4,S,1
184,185,"Kink-Heilmann, Miss. Luise Gretchen",female,4.00,0,2,315153,3,22.0250,NaN,S,1
193,194,"Navratil, Master. Michel M",male,3.00,1,1,230080,2,26.0000,F2,S,1
233,234,"Asplund, Miss. Lillian Gertrud",female,5.00,4,2,347077,3,31.3875,NaN,S,1
237,238,"Collyer, Miss. Marjorie ""Lottie""",female,8.00,0,2,C.A. 31921,2,26.2500,NaN,S,1
261,262,"Asplund, Master. Edvin Rojj Felix",male,3.00,4,2,347077,3,31.3875,NaN,S,1
278,279,"Rice, Master. Eric",male,7.00,4,1,382652,3,29.1250,NaN,Q,0
297,298,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,1,151.5500,C22 C26,S,0
305,306,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,1,151.5500,C22 C26,S,1
340,341,"Navratil, Master. Edmond Roger",male,2.00,1,1,230080,2,26.0000,F2,S,1
374,375,"Palsson, Miss. Stina Viola",female,3.00,3,1,349909,3,21.0750,NaN,S,0
386,387,"Goodwin, Master. Sidney Leonard",male,1.00,5,2,CA 2144,3,46.9000,NaN,S,0
419,420,"Van Impe, Miss. Catharina",female,10.00,0,2,345773,3,24.1500,NaN,S,0
445,446,"Dodge, Master. Washington",male,4.00,0,2,33638,1,81.8583,A34,S,1
480,481,"Goodwin, Master. Harold Victor",male,9.00,5,2,CA 2144,3,46.9000,NaN,S,0
530,531,"Quick, Miss. Phyllis May",female,2.00,1,1,26360,2,26.0000,NaN,S,1
535,536,"Hart, Miss. Eva Miriam",female,7.00,0,2,F.C.C. 13529,2,26.2500,NaN,S,1
541,542,"Andersson, Miss. Ingeborg Constanzia",female,9.00,4,2,347082,3,31.2750,NaN,S,0
549,550,"Davies, Master. John Morgan Jr",male,8.00,1,1,C.A. 33112,2,36.7500,NaN,S,1
618,619,"Becker, Miss. Marion Louise",female,4.00,2,1,230136,2,39.0000,F4,S,1
634,635,"Skoog, Miss. Mabel",female,9.00,3,2,347088,3,27.9000,NaN,S,0
642,643,"Skoog, Miss. Margit Elizabeth",female,2.00,3,2,347088,3,27.9000,NaN,S,0
720,721,"Harper, Miss. Annie Jessie ""Nina""",female,6.00,0,1,248727,2,33.0000,NaN,S,1
750,751,"Wells, Miss. Joan",female,4.00,1,1,29103,2,23.0000,NaN,S,1
787,788,"Rice, Master. George Hugh",male,8.00,4,1,382652,3,29.1250,NaN,Q,0
788,789,"Dean, Master. Bertram Vere",male,1.00,1,2,C.A. 2315,3,20.5750,NaN,S,1
813,814,"Andersson, Miss. Ebba Iris Alfrida",female,6.00,4,2,347082,3,31.2750,NaN,S,0
819,820,"Skoog, Master. Karl Thorsten",male,10.00,3,2,347088,3,27.9000,NaN,S,0
824,825,"Panula, Master. Urho Abraham",male,2.00,4,1,3101295,3,39.6875,NaN,S,0
827,828,"Mallet, Master. Andre",male,1.00,0,2,S.C./PARIS 2079,2,37.0042,NaN,C,1
850,851,"Andersson, Master. Sigvard Harald Elias",male,4.00,4,2,347082,3,31.2750,NaN,S,0

<div class="alert alert-success">
    <b>EXERCISE 24</b>: 나이가 결측치인 데이터를 출력하세요.
</div>

In [68]:
df[df['Age'].isna()]

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
5,6,"Moran, Mr. James",male,NaN,0,0,330877,3,8.4583,NaN,Q,0
17,18,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,2,13.0000,NaN,S,1
19,20,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,3,7.2250,NaN,C,1
26,27,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,3,7.2250,NaN,C,0
28,29,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,3,7.8792,NaN,Q,1
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,"Razi, Mr. Raihed",male,NaN,0,0,2629,3,7.2292,NaN,C,0
863,864,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,3,69.5500,NaN,S,0
868,869,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,3,9.5000,NaN,S,0
878,879,"Laleff, Mr. Kristo",male,NaN,0,0,349217,3,7.8958,NaN,S,0
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,3,23.4500,NaN,S,0

<div class="alert alert-success">
    <b>EXERCISE 25</b>: 나이를 기준으로 오름차순 정렬하세요.
</div>

In [69]:
df.sort_values(by='Age', ascending=True)

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
803,804,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,3,8.5167,NaN,C,1
755,756,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,2,14.5000,NaN,S,1
644,645,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,3,19.2583,NaN,C,1
469,470,"Baclini, Miss. Helene Barbara",female,0.75,2,1,2666,3,19.2583,NaN,C,1
78,79,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,2,29.0000,NaN,S,1
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,"Razi, Mr. Raihed",male,NaN,0,0,2629,3,7.2292,NaN,C,0
863,864,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,3,69.5500,NaN,S,0
868,869,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,3,9.5000,NaN,S,0
878,879,"Laleff, Mr. Kristo",male,NaN,0,0,349217,3,7.8958,NaN,S,0
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,3,23.4500,NaN,S,0

<div class="alert alert-success">
    <b>EXERCISE 26</b>: 요금을 기준으로 내림차순 정렬하고 상위 5명만 출력하세요.
</div>

In [70]:
df.sort_values(by="Fare", ascending=False).head()

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
679,680,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,1,512.3292,B51 B53 B55,C,1
258,259,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,1,512.3292,NaN,C,1
737,738,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,1,512.3292,B101,C,1
88,89,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,1,263.0000,C23 C25 C27,S,1
438,439,"Fortune, Mr. Mark",male,64.0,1,4,19950,1,263.0000,C23 C25 C27,S,0

<div class="alert alert-success">
    <b>EXERCISE 27</b>: 성별로 그룹화하여 생존률 평균을 구하세요.
</div>

In [72]:
df[['Sex', 'Survived']].groupby('Sex').mean()

        Survived
Sex
female  0.742038
male    0.188908

<div class="alert alert-success">
    <b>EXERCISE 28</b>: Pclass별 평균 나이를 구하세요.
</div>

In [73]:
df[['Pclass', 'Age']].groupby('Pclass').mean()

              Age
Pclass
1       38.233441
2       29.877630
3       25.140620

<div class="alert alert-success">
    <b>EXERCISE 29</b>: 'Age'에 10을 더한 값을 새로운 컬럼 'Age_plus_10'으로 추가하세요.
</div>

<div class="alert alert-success">
    <b>EXERCISE 30</b>: 'Age'가 18 이상이면 '성인', 아니면 '미성년'으로 분류하는 컬럼을 추가하세요.
</div>

In [75]:
df['Age'].apply(lambda x: "성인" if x >= 18 else "미성년")

0       성인
1       성인
2       성인
3       성인
4       성인
      ...
886     성인
887     성인
888    미성년
889     성인
890     성인
Name: Age, Length: 891, dtype: str

In [76]:
df['isadult'] = df['Age'].apply(lambda x: "성인" if x >= 18 else "미성년")

In [77]:
df

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived,isadult
0,1,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,3,7.2500,NaN,S,0,성인
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,1,71.2833,C85,C,1,성인
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,3,7.9250,NaN,S,1,성인
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,1,53.1000,C123,S,1,성인
4,5,"Allen, Mr. William Henry",male,35.0,0,0,373450,3,8.0500,NaN,S,0,성인
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",male,27.0,0,0,211536,2,13.0000,NaN,S,0,성인
887,888,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,1,30.0000,B42,S,1,성인
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,3,23.4500,NaN,S,0,미성년
889,890,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,1,30.0000,C148,C,1,성인
890,891,"Dooley, Mr. Patrick",male,32.0,0,0,370376,3,7.7500,NaN,Q,0,성인

<div class="alert alert-success">
    <b>EXERCISE 31</b>: 'Age'의 결측치를 평균으로 채우세요.
</div>

In [82]:
na_idx = df[df['Age'].isna()].index

In [80]:
df["Age"] = df["Age"].fillna(df["Age"].mean())
df

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived,isadult
0,1,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,3,7.2500,NaN,S,0,성인
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,1,71.2833,C85,C,1,성인
2,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,3,7.9250,NaN,S,1,성인
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,1,53.1000,C123,S,1,성인
4,5,"Allen, Mr. William Henry",male,35.000000,0,0,373450,3,8.0500,NaN,S,0,성인
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,2,13.0000,NaN,S,0,성인
887,888,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,1,30.0000,B42,S,1,성인
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,3,23.4500,NaN,S,0,미성년
889,890,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,1,30.0000,C148,C,1,성인
890,891,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,3,7.7500,NaN,Q,0,성인

In [83]:
df.loc[na_idx]

Empty DataFrame
Columns: [PassengerId, Name, Sex, Age, SibSp, Parch, Ticket, Pclass, Fare, Cabin, Embarked, Survived, isadult]
Index: []

<div class="alert alert-success">
    <b>EXERCISE 32</b>: 'Cabin' 컬럼의 결측치를 'Unknown'으로 채우세요.
</div>

In [87]:
Cabin_nan_idx = df[df['Cabin'].isna()].index

In [88]:
df['Cabin'] = df['Cabin'].fillna("Unknown")

In [89]:
df.loc[Cabin_nan_idx]

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived,isadult
0,1,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,3,7.2500,Unknown,S,0,성인
2,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,3,7.9250,Unknown,S,1,성인
4,5,"Allen, Mr. William Henry",male,35.000000,0,0,373450,3,8.0500,Unknown,S,0,성인
5,6,"Moran, Mr. James",male,29.699118,0,0,330877,3,8.4583,Unknown,Q,0,미성년
7,8,"Palsson, Master. Gosta Leonard",male,2.000000,3,1,349909,3,21.0750,Unknown,S,0,미성년
...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,885,"Sutehall, Mr. Henry Jr",male,25.000000,0,0,SOTON/OQ 392076,3,7.0500,Unknown,S,0,성인
885,886,"Rice, Mrs. William (Margaret Norton)",female,39.000000,0,5,382652,3,29.1250,Unknown,Q,0,성인
886,887,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,2,13.0000,Unknown,S,0,성인
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,3,23.4500,Unknown,S,0,미성년
890,891,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,3,7.7500,Unknown,Q,0,성인

<div class="alert alert-success">
    <b>EXERCISE 33</b>: 중복된 'Ticket' 값을 제거하고 몇 개가 남는지 출력하세요.
</div>

In [95]:
# 중복이 있는지 확인하기
df[df['Ticket'].duplicated()]

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived,isadult
24,25,"Palsson, Miss. Torborg Danira",female,8.000000,3,1,349909,3,21.0750,Unknown,S,0,미성년
71,72,"Goodwin, Miss. Lillian Amy",female,16.000000,5,2,CA 2144,3,46.9000,Unknown,S,0,미성년
88,89,"Fortune, Miss. Mabel Helen",female,23.000000,3,2,19950,1,263.0000,C23 C25 C27,S,1,성인
117,118,"Turpin, Mr. William John Robert",male,29.000000,1,0,11668,2,21.0000,Unknown,S,0,성인
119,120,"Andersson, Miss. Ellis Anna Maria",female,2.000000,4,2,347082,3,31.2750,Unknown,S,0,미성년
...,...,...,...,...,...,...,...,...,...,...,...,...,...
876,877,"Gustafsson, Mr. Alfred Ossian",male,20.000000,0,0,7534,3,9.8458,Unknown,S,0,성인
879,880,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.000000,0,1,11767,1,83.1583,C50,C,1,성인
880,881,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.000000,0,1,230433,2,26.0000,Unknown,S,1,성인
885,886,"Rice, Mrs. William (Margaret Norton)",female,39.000000,0,5,382652,3,29.1250,Unknown,Q,0,성인
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,3,23.4500,Unknown,S,0,미성년

In [98]:
# 없애기
df.drop_duplicates(subset = 'Ticket')

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived,isadult
0,1,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,3,7.2500,Unknown,S,0,성인
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,1,71.2833,C85,C,1,성인
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,3,7.9250,Unknown,S,1,성인
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,1,53.1000,C123,S,1,성인
4,5,"Allen, Mr. William Henry",male,35.0,0,0,373450,3,8.0500,Unknown,S,0,성인
...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,885,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,3,7.0500,Unknown,S,0,성인
886,887,"Montvila, Rev. Juozas",male,27.0,0,0,211536,2,13.0000,Unknown,S,0,성인
887,888,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,1,30.0000,B42,S,1,성인
889,890,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,1,30.0000,C148,C,1,성인
890,891,"Dooley, Mr. Patrick",male,32.0,0,0,370376,3,7.7500,Unknown,Q,0,성인

In [99]:
# 개수
len(df.drop_duplicates(subset = 'Ticket'))

681

<div class="alert alert-success">
    <b>EXERCISE 34</b>: 'Embarked' 컬럼의 고유값과 각각의 개수를 출력하세요.
</div>

In [100]:
df['Embarked'].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

<div class="alert alert-success">
    <b>EXERCISE 35</b>: 인덱스를 'PassengerId'로 설정하세요.
</div>

In [103]:
df = df.set_index('PassengerId')
df

,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived,isadult
PassengerId,,,,,,,,,,,,
1,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,3,7.2500,Unknown,S,0,성인
2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,1,71.2833,C85,C,1,성인
3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,3,7.9250,Unknown,S,1,성인
4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,1,53.1000,C123,S,1,성인
5,"Allen, Mr. William Henry",male,35.000000,0,0,373450,3,8.0500,Unknown,S,0,성인
...,...,...,...,...,...,...,...,...,...,...,...,...
887,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,2,13.0000,Unknown,S,0,성인
888,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,1,30.0000,B42,S,1,성인
889,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,3,23.4500,Unknown,S,0,미성년
890,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,1,30.0000,C148,C,1,성인
891,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,3,7.7500,Unknown,Q,0,성인

<div class="alert alert-success">
    <b>EXERCISE 36</b>: 인덱스를 초기화하세요.
</div>

In [105]:
df = df.reset_index()
df

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived,isadult
0,1,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,3,7.2500,Unknown,S,0,성인
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,1,71.2833,C85,C,1,성인
2,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,3,7.9250,Unknown,S,1,성인
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,1,53.1000,C123,S,1,성인
4,5,"Allen, Mr. William Henry",male,35.000000,0,0,373450,3,8.0500,Unknown,S,0,성인
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,2,13.0000,Unknown,S,0,성인
887,888,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,1,30.0000,B42,S,1,성인
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,3,23.4500,Unknown,S,0,미성년
889,890,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,1,30.0000,C148,C,1,성인
890,891,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,3,7.7500,Unknown,Q,0,성인

<div class="alert alert-success">
    <b>EXERCISE 37</b>: 성별과 Pclass의 생존률을 피벗 테이블로 만드세요.
</div>

In [107]:
df.pivot_table(values='Survived', index="Pclass", columns='Sex')

Sex       female      male
Pclass
1       0.968085  0.368852
2       0.921053  0.157407
3       0.500000  0.135447

<div class="alert alert-success">
    <b>EXERCISE 38</b>: groupby()를 사용하여 각 성별(sex)의 평균 나이(age)를 구하세요.
</div>

In [108]:
df[['Sex', 'Age']].groupby('Sex').mean()

              Age
Sex
female  28.216730
male    30.505824

<div class="alert alert-success">
    <b>EXERCISE 39</b>: 전체 승객(passenger)의 평균 생존율을 구하세요.
</div>

In [110]:
df['Survived'].mean() * 100

np.float64(38.38383838383838)

<div class="alert alert-success">
    <b>EXERCISE 40</b>: 25세 이하 승객의 생존율을 구하세요. (힌트: 불리언 인덱싱)
</div>

In [115]:
df.loc[df["Age"] <= 25, "Survived"].mean() * 100

np.float64(41.19601328903654)

<div class="alert alert-success">
    <b>EXERCISE 41</b>: 남성의 생존율을 구하세요. 여성의 생존율을 구하세요. (힌트: 불리언 인덱싱)
</div>

In [119]:
print("남성의 생존율: ", df.loc[(df['Sex'] == "male"), 'Survived'].mean() * 100)
print("여성의 생존율: ",df.loc[(df['Sex'] == "female"), 'Survived'].mean() * 100)

남성의 생존율:  18.890814558058924
여성의 생존율:  74.20382165605095

<div class="alert alert-success">
    <b>EXERCISE 42</b>: 생존율을 구하는 함수가 작성되어 있습니다. 성별 생존율을 groupby를 활용해 구하기 위해 ?부분을 알맞게 채워주세요.
</div>

In [120]:
def survival_ratio(survived):
    return survived.sum() / len(survived)

In [121]:
# 1안
df[['Sex', 'Survived']].groupby('Sex').agg(survival_ratio)

        Survived
Sex
female  0.742038
male    0.188908

In [130]:
# 2안
df.groupby("Sex")["Survived"].mean() * 100
df.groupby("Sex")[["Survived"]].mean() * 100

# 대괄호 하나 → Series
# 대괄호 두 개 → DataFrame

         Survived
Sex
female  74.203822
male    18.890815