# pandas
https://jupyterlab.readthedocs.io/en/stable/getting_started/starting.html
* numpy를 내부적으로 활용함
* 데이터 분석에 특화된 데이터 구조 제공(DataFrame, Series)
* 다양한 데이터 분석 함수 제공
* 데이터베이스에 쉽게 연결 가능
* json,html의 table 요소를 DataFrame으로 쉽게 변경 가능

In [1]:
# !pip install pandas

# pandas에서 다루는 데이터 타입 2가지
## 1) DataFrame: 2차원의 표 형식 데이터
* python의 dict와도 비슷
* 하나의 key에 list형태의 value가 매칭되어 있는 형태
```python 
{key : [value1, value2, value3], key2 : [value1, value2, value3]}
```
## 2) Series: 1차원의 벡터 형식 데이터
* python의 list, tuple, numpy의 ndarray와 비슷
* 이름이 있는 list

In [2]:
import pandas as pd

# 데이터프레임 만들기
```python
pd.DataFrame(
    {'이름' : ['홍길동', '둘리', '또치', '도우너'],
     '주소' : ['서울', '의정부', '고양', '성남'],
     '취미' : ['음악감상', '놀기', '달리기', '바이올린']}
```

In [3]:
df = pd.DataFrame(
    {'이름' : ['홍길동', '둘리', '또치', '도우너'],
     '주소' : ['서울', '의정부', '고양', '성남'],
     '취미' : ['음악감상', '놀기', '달리기', '바이올린']})
df

    이름   주소    취미
0  홍길동   서울  음악감상
1   둘리  의정부    놀기
2   또치   고양   달리기
3  도우너   성남  바이올린

In [4]:
df.shape

(4, 3)

In [5]:
df.ndim

2

In [6]:
df.size

12

In [8]:
df['이름'].dtype

dtype('O')

# Series 만들기
```python
pd.Series([리스트/튜플]), name = '컬럼명')
```
* 이름을 가지고 있는 list / 벡터
* DataFrame에서 컬럼 1개를 잘라온 상태

In [9]:
ages = pd.Series([22,53,35], name='나이')
ages

0    22
1    53
2    35
Name: 나이, dtype: int64

In [10]:
ages.min()

np.int64(22)

In [11]:
ages.max()

np.int64(53)

In [13]:
ages.sum()

np.int64(110)

In [15]:
ages.cumsum() # 누적

0     22
1     75
2    110
Name: 나이, dtype: int64

In [16]:
ages.mean()

np.float64(36.666666666666664)

In [17]:
ages.median()

np.float64(35.0)

# pandas에서 자료 불러오기, 저장하기
* csv, tsv, excel, json, html, sql
* pd.read_확장자명(파일경로, 옵션)

* 엑셀 파일 불러오기

In [21]:
# !pip install openpyxl

In [48]:
# 문자열은 read.json
df_excel = pd.read_excel("./data/Online Retail.xlsx")
df_excel

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

In [26]:
df_csv = pd.read_csv("./data/Online Retail.csv")
df_csv

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

In [29]:
%%time # 셀 전체 실행 시간
df_excel2 = pd.read_excel("./data/아파트(매매)_실거래가_20240806113828.xlsx", header=12)
df_excel2
# 파일 안에 쓸데 없는 설명문구가 있으면 에러가 떠요 ~
# 13번 행부터 의미 있는 정보임

C:\Users\Admin\miniforge3\envs\fintech\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

CPU times: total: 31.8 s
Wall time: 32.4 s

,NO,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),...,층,매수자,매도자,건축년도,도로명,해제사유발생일,거래유형,중개사소재지,등기일자,주택유형
0,1,서울특별시 영등포구 당산동5가,42,42,0,당산삼성래미안4차,115.7800,202407,31,"139,000",...,4,개인,개인,2003,당산로 214,-,직거래,-,-,아파트
1,2,강원특별자치도 원주시 지정면 가곡리,1512,1512,0,원주롯데캐슬골드파크1차(5단지),84.9644,202407,31,"38,900",...,10,개인,개인,2019,신지정로 250,20240802,중개거래,강원 원주시,-,아파트
2,3,대구광역시 달성군 화원읍 구라리,1650,1650,0,대곡역래미안,84.5958,202407,31,"29,500",...,11,개인,개인,2007,비슬로539길 35,-,중개거래,대구 달성군,-,아파트
3,4,광주광역시 남구 진월동,312-7,312,7,광명,70.6250,202407,31,"16,900",...,1,개인,개인,1998,광복마을길 63,-,중개거래,광주 남구,-,아파트
4,5,광주광역시 남구 진월동,331-93,331,93,중흥,84.8400,202407,31,"17,500",...,13,개인,개인,1992,서문대로749번마길 30,-,직거래,-,24.07.31,아파트
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37575,37576,서울특별시 송파구 장지동,849,849,0,송파파인타운3단지,84.9800,202407,1,"117,500",...,14,개인,개인,2008,충민로 152,-,중개거래,서울 송파구,-,아파트
37576,37577,부산광역시 사상구 모라동,552,552,0,백양그린,41.3000,202407,1,"7,000",...,8,개인,개인,1992,모라로110번길 88,-,중개거래,부산 사상구,24.07.10,아파트
37577,37578,광주광역시 광산구 비아동,152-5,152,5,호반,59.8800,202407,1,"15,400",...,5,개인,개인,1998,비아로 185,-,중개거래,광주 광산구,24.07.26,아파트
37578,37579,부산광역시 사상구 모라동,552,552,0,백양그린,41.3000,202407,1,"7,500",...,10,개인,개인,1992,모라로110번길 88,-,중개거래,부산 사상구,24.07.19,아파트
37579,37580,대구광역시 북구 읍내동,1366-2,1366,2,칠곡보성,84.9800,202407,1,"21,000",...,9,개인,개인,1992,구암로21길 26,-,중개거래,대구 북구,-,아파트

In [33]:
# 빨리 읽고 싶으면 excel을 csv로 바꿔야 함
df_excel2.to_csv("./data/아파트(매매)_실거래가_20240806113828.csv", index=False, encoding="utf-8-sig")

In [31]:
%%time
df_csv2 = pd.read_csv("./data/아파트(매매)_실거래가_20240806113828.csv")
df_csv2

CPU times: total: 266 ms
Wall time: 308 ms

,NO,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),...,층,매수자,매도자,건축년도,도로명,해제사유발생일,거래유형,중개사소재지,등기일자,주택유형
0,1,서울특별시 영등포구 당산동5가,42,42,0,당산삼성래미안4차,115.7800,202407,31,"139,000",...,4,개인,개인,2003,당산로 214,-,직거래,-,-,아파트
1,2,강원특별자치도 원주시 지정면 가곡리,1512,1512,0,원주롯데캐슬골드파크1차(5단지),84.9644,202407,31,"38,900",...,10,개인,개인,2019,신지정로 250,20240802,중개거래,강원 원주시,-,아파트
2,3,대구광역시 달성군 화원읍 구라리,1650,1650,0,대곡역래미안,84.5958,202407,31,"29,500",...,11,개인,개인,2007,비슬로539길 35,-,중개거래,대구 달성군,-,아파트
3,4,광주광역시 남구 진월동,312-7,312,7,광명,70.6250,202407,31,"16,900",...,1,개인,개인,1998,광복마을길 63,-,중개거래,광주 남구,-,아파트
4,5,광주광역시 남구 진월동,331-93,331,93,중흥,84.8400,202407,31,"17,500",...,13,개인,개인,1992,서문대로749번마길 30,-,직거래,-,24.07.31,아파트
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37575,37576,서울특별시 송파구 장지동,849,849,0,송파파인타운3단지,84.9800,202407,1,"117,500",...,14,개인,개인,2008,충민로 152,-,중개거래,서울 송파구,-,아파트
37576,37577,부산광역시 사상구 모라동,552,552,0,백양그린,41.3000,202407,1,"7,000",...,8,개인,개인,1992,모라로110번길 88,-,중개거래,부산 사상구,24.07.10,아파트
37577,37578,광주광역시 광산구 비아동,152-5,152,5,호반,59.8800,202407,1,"15,400",...,5,개인,개인,1998,비아로 185,-,중개거래,광주 광산구,24.07.26,아파트
37578,37579,부산광역시 사상구 모라동,552,552,0,백양그린,41.3000,202407,1,"7,500",...,10,개인,개인,1992,모라로110번길 88,-,중개거래,부산 사상구,24.07.19,아파트
37579,37580,대구광역시 북구 읍내동,1366-2,1366,2,칠곡보성,84.9800,202407,1,"21,000",...,9,개인,개인,1992,구암로21길 26,-,중개거래,대구 북구,-,아파트

In [45]:
# df_json = pd.read_json("./data/서울특별시_관광지입장정보_2011_2016.json")
# df_json

In [38]:
import json
with open("../03 python/data/전국치킨집리스트.json") as f:
    df_json3 = f.read()
    df_json3 = json.loads(df_json3)

In [42]:
# df_json3[0]['body']['items']

In [43]:
# df_json2 = pd.read_json("../03 python/data/전국치킨집리스트.json")
# df_json2

In [49]:
# 정보가 안에 숨어있는 건 리스트로 꺼내고, normalize로 처리
result = []
for page in df_json3:
    temp_df = pd.json_normalize(page['body']['items'])
    result.append(temp_df)
final_result = pd.concat(result)
final_result

,bizesId,bizesNm,brchNm,indsLclsCd,indsLclsNm,indsMclsCd,indsMclsNm,indsSclsCd,indsSclsNm,ksicCd,...,bldMngNo,bldNm,rdnmAdr,oldZipcd,newZipcd,dongNo,flrNo,hoNo,lon,lat
0,10027626,장모님치킨가창점,가창점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,2771031024101200004036858,,대구광역시 달성군 가창면 가창동로 6,711861,42938,,1,,128.644459,35.782663
1,10098244,짱구피자치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4125010300102680011008557,,경기도 동두천시 못골로 30,483030,11320,,,,127.065903,37.901262
2,10099459,쭈노치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4157025324105380008019970,,경기도 김포시 고촌읍 장차로13번길 18,415811,10126,,1,,126.769859,37.603752
3,10136167,치킨뱅이,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4213011000108300006022278,,강원도 원주시 금불3길 5,220938,26423,,1,,127.932025,37.348358
4,10136346,치킨월드율량점,율량점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4311111500108060000045239,,충청북도 청주시 청원구 공항로138번길 53,363818,28328,,1,,127.487586,36.669816
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,9829515,아리치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4125010200106740003008662,,경기도 동두천시 거북마루로 6,483020,11348,,1,,127.046713,37.895702
60,9851302,애니치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4785031036104090002008916,,경상북도 칠곡군 지천면 신동로 147,718821,39864,,,,128.488717,35.956631
61,9867543,에디슨치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,1135010600103590001010681,중계5단지주공아파트,서울특별시 노원구 중계로 230,139781,01713,,1,,127.075031,37.651004
62,9918905,오븐에꾸운닭장유점,장유점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4825031027103150002091993,재영프라자,경상남도 김해시 삼문로 26,621280,51004,,1,,128.803565,35.192491
63,9967953,웰빙치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4213011100101360002016167,,강원도 원주시 상지대길 43,220954,26342,,1,,127.937290,37.369591

In [46]:
df_json2 = pd.json_normalize(df_json3[0]['body']['items'])
df_json2

,bizesId,bizesNm,brchNm,indsLclsCd,indsLclsNm,indsMclsCd,indsMclsNm,indsSclsCd,indsSclsNm,ksicCd,...,bldMngNo,bldNm,rdnmAdr,oldZipcd,newZipcd,dongNo,flrNo,hoNo,lon,lat
0,10027626,장모님치킨가창점,가창점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,2771031024101200004036858,,대구광역시 달성군 가창면 가창동로 6,711861,42938,,1,,128.644459,35.782663
1,10098244,짱구피자치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4125010300102680011008557,,경기도 동두천시 못골로 30,483030,11320,,,,127.065903,37.901262
2,10099459,쭈노치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4157025324105380008019970,,경기도 김포시 고촌읍 장차로13번길 18,415811,10126,,1,,126.769859,37.603752
3,10136167,치킨뱅이,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4213011000108300006022278,,강원도 원주시 금불3길 5,220938,26423,,1,,127.932025,37.348358
4,10136346,치킨월드율량점,율량점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4311111500108060000045239,,충청북도 청주시 청원구 공항로138번길 53,363818,28328,,1,,127.487586,36.669816
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,11927120,두두두마리치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4719034028104640013062144,,경상북도 구미시 해평면 강동로 1671,730873,39154,,1,,128.390989,36.199637
996,11927310,호식이두마리치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4272025029104520007040192,,강원도 홍천군 홍천읍 남산강변로 32,250930,25149,,1,,127.882012,37.685865
997,11927491,또봉이치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,2820010200100690027020930,,인천광역시 남동구 풀무로 9-2,405230,21510,,1,,126.709187,37.469419
998,11927616,투마리치킨하늘도시점,하늘도시점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,2811014600100330008000001,,인천광역시 중구 운중로 85-1,400811,22359,,1,,126.542880,37.493596
999,11927757,노랑통닭,구리수택점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4131010500104480006008791,구리신성미소지움,경기도 구리시 이문안로 81,471030,11941,101,1,,127.140380,37.592408

In [51]:
df_html = pd.read_html("../06 Marchine_learning_Deep_learning/data/corpList.htm")
df_html

[    Unnamed: 0                             Unnamed: 1  \
 0     한국제15호스팩                             금융 지원 서비스업
 1       에스오에스랩  측정, 시험, 항해, 제어 및 기타 정밀기기 제조업; 광학기기 제외
 2   미래에셋비전스팩6호                             금융 지원 서비스업
 3   에이치엠씨제7호스팩                             금융 지원 서비스업
 4        파라다이스                     유원지 및 기타 오락관련 서비스업
 5       한중엔시에스      전동기, 발전기 및 전기 변환 · 공급 · 제어 장치 제조업
 6     KB제29호스팩                             금융 지원 서비스업
 7   미래에셋비전스팩5호                             금융 지원 서비스업
 8     씨어스테크놀로지                             의료용 기기 제조업
 9     한국제14호스팩                             금융 지원 서비스업
 10   디비금융스팩12호                                 기타 금융업
 11        라메디텍                             의료용 기기 제조업
 12       그리드위즈                 그외 기타 전문, 과학 및 기술 서비스업
 13       다원넥스뷰                        사진장비 및 광학기기 제조업
 14  미래에셋비전스팩4호                             금융 지원 서비스업

                                            Unnamed: 2  Unnamed: 3 Unnamed: 4  \
 0                                              기업인수합병  2024-06-26        12월
 1                                산업용 및 차량용 라이다(LiDAR)  2024-06-25        12월
 2                                              기업인수합병  2024-06-24        12월
 3                                                기타금융  2024-06-24        12월
 4                                      카지노, 호텔, 복합리조트  2024-06-24        12월
 5   수냉식 냉각시스템 ESS Parts, 공랭식 ESS Module Parts, EV ...  2024-06-24        12월
 6                                              기업인수합병  2024-06-21        12월
 7                                              기업인수합병  2024-06-19        12월
 8                                심전도검사솔루션 입원환자모니터링솔루션  2024-06-19        12월
 9                                              기업인수합병  2024-06-19        12월
 10                                          기업인수 및 합병  2024-06-18        12월
 11                                초소형 레이저 의료기기 및 미용기기  2024-06-17        12월
 12                             수요관리 서비스, 전기차 충전기 모뎀 등  2024-06-14        12월
 13                   LSMB(Laser Micro Bonding System)  2024-06-11        12월
 14                                  기업인수목적회사(기타금융서비스)  2024-05-29        12월

    Unnamed: 5 Unnamed: 6 Unnamed: 7
 0          유한        NaN      서울특별시
 1         정지성    홈페이지 보기      광주광역시
 2         정명훈        NaN      서울특별시
 3         강신명        NaN      서울특별시
 4       최종환..    홈페이지 보기      서울특별시
 5         김환식    홈페이지 보기       경상북도
 6         서영화        NaN      서울특별시
 7         김대호        NaN      서울특별시
 8         이영신    홈페이지 보기        경기도
 9         변성환        NaN      서울특별시
 10        김창희        NaN      서울특별시
 11        최종석        NaN      서울특별시
 12        김구환    홈페이지 보기        경기도
 13        남기중    홈페이지 보기        경기도
 14        김정수        NaN      서울특별시  ]

# DB에서 자료 읽어오기

In [53]:
import os

In [54]:
dbid = os.getenv("dbid")
dbpw = os.getenv("dbpw")
host = os.getenv("host")
port = os.getenv("port")

In [59]:
# %pip install sqlalchemy pymysql
from sqlalchemy import create_engine
import pymysql

In [61]:
pymysql.install_as_MySQLdb()

In [63]:
engine = create_engine(f"mysqltpymysql://{dbid}:{dbpw}@{host}:{port}/exchange_rate")
conn = engine.connect()
df_sql = pd.read_sql("exchange_rate", con=conn)
conn.close()
df_sql

ValueError: invalid literal for int() with base 10: 'None'

In [64]:
from dbio import from_db

ModuleNotFoundError: No module named 'dbio'

In [ ]:
df_sql2 = from_df("exchange")

# 타이타닉 데이터셋으로 pandas 기능 익히기

In [65]:
df = pd.read_csv("./data/Titanic_train.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [66]:
print(df)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]

## 데이터 일부만 보기
* head(숫자), tail(숫자)
* 기본 값을 5개 행만 출력
* 60행까지 출력 가능

In [72]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [74]:
df.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

# .info()
* 컬럼명, null 이 아닌 데이터 개수, 데이터 타입을 동시에 출력

In [75]:
df.info()
# Rangeindex : 전체 행 개수
# non-null : null 이 아닌 행

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

# .describe()
* 데이터 프레임의 숫자 데이터의 기초통계를 보여주는 함수
* count, mean, std, min, 25%, 50%, 75%, max
* .describe(include="All"): 문자형/카테고리형 데이터에서 유일값, 최빈값 출력

In [77]:
df.describe() # 숫자 데이터만 보여줌

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [79]:
df.describe(include = "all")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,891.000000,891.000000,891.000000,891,891,714.000000,891.000000,891.000000,891,891.000000,204,889
unique,NaN,NaN,NaN,891,2,NaN,NaN,NaN,681,NaN,147,3
top,NaN,NaN,NaN,"Dooley, Mr. Patrick",male,NaN,NaN,NaN,347082,NaN,G6,S
freq,NaN,NaN,NaN,1,577,NaN,NaN,NaN,7,NaN,4,644
mean,446.000000,0.383838,2.308642,NaN,NaN,29.699118,0.523008,0.381594,NaN,32.204208,NaN,NaN
std,257.353842,0.486592,0.836071,NaN,NaN,14.526497,1.102743,0.806057,NaN,49.693429,NaN,NaN
min,1.000000,0.000000,1.000000,NaN,NaN,0.420000,0.000000,0.000000,NaN,0.000000,NaN,NaN
25%,223.500000,0.000000,2.000000,NaN,NaN,20.125000,0.000000,0.000000,NaN,7.910400,NaN,NaN
50%,446.000000,0.000000,3.000000,NaN,NaN,28.000000,0.000000,0.000000,NaN,14.454200,NaN,NaN
75%,668.500000,1.000000,3.000000,NaN,NaN,38.000000,1.000000,0.000000,NaN,31.000000,NaN,NaN
max,891.000000,1.000000,3.000000,NaN,NaN,80.000000,8.000000,6.000000,NaN,512.329200,NaN,NaN

# pandas 데이터 프레임에서 일부 자료만 추출하기

* 데이터 프레임에서 1개 컬럼만 가져오기

In [84]:
print(df['Name'], type(df['Name']))
print(df['Name'].shape)

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object <class 'pandas.core.series.Series'>
(891,)

* 2개 이상 컬럼을 가져오기

In [85]:
df[['Age', 'Name']]

      Age                                               Name
0    22.0                            Braund, Mr. Owen Harris
1    38.0  Cumings, Mrs. John Bradley (Florence Briggs Th...
2    26.0                             Heikkinen, Miss. Laina
3    35.0       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4    35.0                           Allen, Mr. William Henry
..    ...                                                ...
886  27.0                              Montvila, Rev. Juozas
887  19.0                       Graham, Miss. Margaret Edith
888   NaN           Johnston, Miss. Catherine Helen "Carrie"
889  26.0                              Behr, Mr. Karl Howell
890  32.0                                Dooley, Mr. Patrick

[891 rows x 2 columns]

# 컬럼명 출럭하기: .columns

In [86]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

# 데이터 프레임에서 일부 컬럼만 가져오기2
* loc = 인덱스 이름과 컬럼명으로 데이터의 일부를 추출해 가져옴
```python
df.loc[시작row인덱스이름:끝row인덱스이름, ['컬럼명1', '컬럼명2']]
```
* iloc = 인덱스 번호를 이용해 슬라이싱으로 데이터의 일부를 가져옴
```python
df.iloc[시작row인덱스번호:끝row인덱스번호+1, 시작column인덱스번호:끝column인덱스번호]
```

* 이름과 나이 컬럼에서 인덱스 100-150번까지만 가져오고 싶을 때

In [90]:
df.loc[100:150, ['Name', 'Age']] # 인덱스는 숫자일수도, 숫자가 아닐수도 있음 주의

                                                  Name   Age
100                            Petranec, Miss. Matilda  28.0
101                   Petroff, Mr. Pastcho ("Pentcho")   NaN
102                          White, Mr. Richard Frasar  21.0
103                         Johansson, Mr. Gustaf Joel  33.0
104                     Gustafsson, Mr. Anders Vilhelm  37.0
105                              Mionoff, Mr. Stoytcho  28.0
106                   Salkjelsvik, Miss. Anna Kristine  21.0
107                             Moss, Mr. Albert Johan   NaN
108                                    Rekic, Mr. Tido  38.0
109                                Moran, Miss. Bertha   NaN
110                     Porter, Mr. Walter Chamberlain  47.0
111                               Zabour, Miss. Hileni  14.5
112                             Barton, Mr. David John  22.0
113                            Jussila, Miss. Katriina  20.0
114                              Attalah, Miss. Malake  17.0
115                              Pekoniemi, Mr. Edvard  21.0
116                               Connors, Mr. Patrick  70.5
117                    Turpin, Mr. William John Robert  29.0
118                           Baxter, Mr. Quigg Edmond  24.0
119                  Andersson, Miss. Ellis Anna Maria   2.0
120                        Hickman, Mr. Stanley George  21.0
121                         Moore, Mr. Leonard Charles   NaN
122                               Nasser, Mr. Nicholas  32.5
123                                Webber, Miss. Susan  32.5
124                        White, Mr. Percival Wayland  54.0
125                       Nicola-Yarred, Master. Elias  12.0
126                                McMahon, Mr. Martin   NaN
127                          Madsen, Mr. Fridtjof Arne  24.0
128                                  Peter, Miss. Anna   NaN
129                                 Ekstrom, Mr. Johan  45.0
130                               Drazenoic, Mr. Jozef  33.0
131                     Coelho, Mr. Domingos Fernandeo  20.0
132     Robins, Mrs. Alexander A (Grace Charity Laury)  47.0
133      Weisz, Mrs. Leopold (Mathilde Francoise Pede)  29.0
134                     Sobey, Mr. Samuel James Hayden  25.0
135                                 Richard, Mr. Emile  23.0
136                       Newsom, Miss. Helen Monypeny  19.0
137                        Futrelle, Mr. Jacques Heath  37.0
138                                Osen, Mr. Olaf Elon  16.0
139                                 Giglio, Mr. Victor  24.0
140                      Boulos, Mrs. Joseph (Sultana)   NaN
141                           Nysten, Miss. Anna Sofia  22.0
142  Hakkarainen, Mrs. Pekka Pietari (Elin Matilda ...  24.0
143                                Burke, Mr. Jeremiah  19.0
144                         Andrew, Mr. Edgardo Samuel  18.0
145                       Nicholls, Mr. Joseph Charles  19.0
146       Andersson, Mr. August Edvard ("Wennerstrom")  27.0
147                   Ford, Miss. Robina Maggie "Ruby"   9.0
148           Navratil, Mr. Michel ("Louis M Hoffman")  36.5
149                  Byles, Rev. Thomas Roussel Davids  42.0
150                         Bateman, Rev. Robert James  51.0

In [93]:
df.iloc[100:151, [3, 5]]

                                                  Name   Age
100                            Petranec, Miss. Matilda  28.0
101                   Petroff, Mr. Pastcho ("Pentcho")   NaN
102                          White, Mr. Richard Frasar  21.0
103                         Johansson, Mr. Gustaf Joel  33.0
104                     Gustafsson, Mr. Anders Vilhelm  37.0
105                              Mionoff, Mr. Stoytcho  28.0
106                   Salkjelsvik, Miss. Anna Kristine  21.0
107                             Moss, Mr. Albert Johan   NaN
108                                    Rekic, Mr. Tido  38.0
109                                Moran, Miss. Bertha   NaN
110                     Porter, Mr. Walter Chamberlain  47.0
111                               Zabour, Miss. Hileni  14.5
112                             Barton, Mr. David John  22.0
113                            Jussila, Miss. Katriina  20.0
114                              Attalah, Miss. Malake  17.0
115                              Pekoniemi, Mr. Edvard  21.0
116                               Connors, Mr. Patrick  70.5
117                    Turpin, Mr. William John Robert  29.0
118                           Baxter, Mr. Quigg Edmond  24.0
119                  Andersson, Miss. Ellis Anna Maria   2.0
120                        Hickman, Mr. Stanley George  21.0
121                         Moore, Mr. Leonard Charles   NaN
122                               Nasser, Mr. Nicholas  32.5
123                                Webber, Miss. Susan  32.5
124                        White, Mr. Percival Wayland  54.0
125                       Nicola-Yarred, Master. Elias  12.0
126                                McMahon, Mr. Martin   NaN
127                          Madsen, Mr. Fridtjof Arne  24.0
128                                  Peter, Miss. Anna   NaN
129                                 Ekstrom, Mr. Johan  45.0
130                               Drazenoic, Mr. Jozef  33.0
131                     Coelho, Mr. Domingos Fernandeo  20.0
132     Robins, Mrs. Alexander A (Grace Charity Laury)  47.0
133      Weisz, Mrs. Leopold (Mathilde Francoise Pede)  29.0
134                     Sobey, Mr. Samuel James Hayden  25.0
135                                 Richard, Mr. Emile  23.0
136                       Newsom, Miss. Helen Monypeny  19.0
137                        Futrelle, Mr. Jacques Heath  37.0
138                                Osen, Mr. Olaf Elon  16.0
139                                 Giglio, Mr. Victor  24.0
140                      Boulos, Mrs. Joseph (Sultana)   NaN
141                           Nysten, Miss. Anna Sofia  22.0
142  Hakkarainen, Mrs. Pekka Pietari (Elin Matilda ...  24.0
143                                Burke, Mr. Jeremiah  19.0
144                         Andrew, Mr. Edgardo Samuel  18.0
145                       Nicholls, Mr. Joseph Charles  19.0
146       Andersson, Mr. August Edvard ("Wennerstrom")  27.0
147                   Ford, Miss. Robina Maggie "Ruby"   9.0
148           Navratil, Mr. Michel ("Louis M Hoffman")  36.5
149                  Byles, Rev. Thomas Roussel Davids  42.0
150                         Bateman, Rev. Robert James  51.0