# pandas
* [https://pandas.pydata.org/docs/getting_started/intro_tutorials/index.html](https://pandas.pydata.org/docs/getting_started/intro_tutorials/index.html)
* numpy를 내부적으로 활용함
* 데이터 분석에 특화된 데이터 구조 제공(DataFrame, Series)
* 다양한 데이터 분석 함수 제공
* 데이터베이스에 쉽게 연결 가능
* json, html의 table 요소를 DataFrame으로 쉽게 변경 가능

In [ ]:
# !pip install pandas

# padas에서 다루는 데이터 타입 2가지
## 1) DataFrame: 2차원의 표 형식 데이터
* python의 dict와도 비슷.
* 하나의 key에 list형태의 value가 매칭되어 있는 형태
```python
{key : [value1, value2, value3], key2 : [value1, value2, value3]}
```
## 2) Series: 1차원의 벡터 형식 데이터
* python의 list, tuple, numpy의 ndarray와 비슷
* 이름이 있는 list

In [1]:
import pandas as pd

# 데이터프레임 만들기
```python
pd.DataFrame(
    {'이름' : ['홍길동', '둘리', '또치', '도우너'],
     '주소' : ['서울', '의정부', '고양', '성남'],
     '취미' : ['음악감상', '놀기', '달리기', '바이올린']
    })
```

In [2]:
df = pd.DataFrame(
    {'이름' : ['홍길동', '둘리', '또치', '도우너'],
     '주소' : ['서울', '의정부', '고양', '성남'],
     '취미' : ['음악감상', '놀기', '달리기', '바이올린']
    })
df

    이름   주소    취미
0  홍길동   서울  음악감상
1   둘리  의정부    놀기
2   또치   고양   달리기
3  도우너   성남  바이올린

In [6]:
df['이름'][2:3]

2    또치
Name: 이름, dtype: object

In [7]:
df.shape

(4, 3)

In [8]:
df.ndim

2

In [9]:
df.size

12

In [11]:
df['이름'].dtype

dtype('O')

# Series 만들기
```python
pd.Series([리스트/튜플], name='컬럼명')
```
* 이름을 가지고 있는 list/ 벡터
* DataFrame에서 컬럼 1개를 잘라온 상태

In [12]:
ages = pd.Series([22,53,35], name='나이')
ages

0    22
1    53
2    35
Name: 나이, dtype: int64

In [13]:
ages[0]

np.int64(22)

In [16]:
ages[0:2:2]

0    22
Name: 나이, dtype: int64

In [17]:
ages[::-1]

2    35
1    53
0    22
Name: 나이, dtype: int64

In [18]:
ages.min()

np.int64(22)

In [19]:
ages.max()

np.int64(53)

In [20]:
ages.sum()

np.int64(110)

In [21]:
ages.cumsum()

0     22
1     75
2    110
Name: 나이, dtype: int64

In [22]:
ages.mean()

np.float64(36.666666666666664)

In [23]:
ages.median()

np.float64(35.0)

# 판다스에서 자료 불러오기, 저장하기
* csv, tsv, excel, json, html, sql
* pd.read_확장자명(파일경로, 옵션)

* excel 파일 불러오기

In [26]:
# !pip install openpyxl

In [24]:
%%time
df_excel = pd.read_excel("./data/Online Retail.xlsx")
df_excel

CPU times: total: 1min
Wall time: 1min 1s

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

* csv 파일 불러오기

In [3]:
%%time
df_csv = pd.read_csv("./data/Online Retail.csv")
# df_csv

NameError: name 'pd' is not defined

In [2]:
%%time
df_excel2 = pd.read_excel("./data/아파트(매매)_실거래가_20240806113828.xlsx", header=12)
# df_excel2

NameError: name 'pd' is not defined

In [31]:
df_excel2.to_csv("./data/아파트(매매)_실거래가_20240806113828.csv", index=False, encoding="utf-8-sig")

In [5]:
%%time
df_csv2 = pd.read_csv("./data/아파트(매매)_실거래가_20240806113828.csv")
# df_csv2

NameError: name 'pd' is not defined

In [4]:
df_json = pd.read_json("./data/서울특별시_관광지입장정보_2011_2016.json")
# df_json

NameError: name 'pd' is not defined

In [6]:
df_json2 = pd.read_json("../03python/data/전국치킨집리스트.json")
# df_json2

NameError: name 'pd' is not defined

In [35]:
import json
with open("../03python/data/전국치킨집리스트.json") as f:
    df_json3 = f.read()
    df_json3 = json.loads(df_json3)

In [9]:
# df_json3[0]['body']['items']

In [7]:
result = []
for page in df_json3:
    temp_df = pd.json_normalize(page['body']['items'])
    result.append(temp_df)
final_result = pd.concat(result)
# final_result

NameError: name 'df_json3' is not defined

In [8]:
df_html = pd.read_html("./data/corpList.htm")
# df_html[0]

NameError: name 'pd' is not defined

# DB에서 자료 읽어오기

In [51]:
import os
from dotenv import load_dotenv
load_dotenv("../05data_scraping/.env")

True

In [56]:
dbid = os.getenv("dbid")
dbpw = os.getenv("dbpw")
host = os.getenv("host")
port = os.getenv("port")

In [57]:
from sqlalchemy import create_engine
import pymysql
pymysql.install_as_MySQLdb()

In [10]:
engine = create_engine(f"mysql+pymysql://{dbid}:{dbpw}@{host}:{port}/exchange_rage_data")
conn = engine.connect()
df_sql = pd.read_sql("exchage_rate", con=conn)
conn.close()
# df_sql

NameError: name 'create_engine' is not defined

In [59]:
from dbio import from_db

In [11]:
df_sql2 = from_db("exchange_rage_data", "exchage_rate")
# df_sql2

NameError: name 'from_db' is not defined

# 타이타닉 데이터셋으로 pandas 기능 익히기

In [12]:
df = pd.read_csv("./data/Titanic_train.csv")
# df

NameError: name 'pd' is not defined

In [62]:
print(df)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]

In [13]:
# display(df)

## 데이터 일부만 보기
* head(숫자), tail(숫자)
* 기본 값을 5개 행만 출력
* 60행까지 출력 가능

In [64]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [65]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [67]:
df.head(1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S

In [14]:
# df.head(60)

# .info()
* 컬럼명, null이 아닌 데이터 개수, 데이터타입을 동시에 출력

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

# .describe()
* 데이터 프레임의 숫자 데이터의 기초통계를 보여주는 함수
* count, mean, std, min, 25%, 50%, 75%, max
* .describe(include="All"): 문자형/카테고리형 데이터에서 유일값, 최빈값 출력

In [73]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [76]:
df.describe(include="all")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,891.000000,891.000000,891.000000,891,891,714.000000,891.000000,891.000000,891,891.000000,204,889
unique,NaN,NaN,NaN,891,2,NaN,NaN,NaN,681,NaN,147,3
top,NaN,NaN,NaN,"Dooley, Mr. Patrick",male,NaN,NaN,NaN,347082,NaN,G6,S
freq,NaN,NaN,NaN,1,577,NaN,NaN,NaN,7,NaN,4,644
mean,446.000000,0.383838,2.308642,NaN,NaN,29.699118,0.523008,0.381594,NaN,32.204208,NaN,NaN
std,257.353842,0.486592,0.836071,NaN,NaN,14.526497,1.102743,0.806057,NaN,49.693429,NaN,NaN
min,1.000000,0.000000,1.000000,NaN,NaN,0.420000,0.000000,0.000000,NaN,0.000000,NaN,NaN
25%,223.500000,0.000000,2.000000,NaN,NaN,20.125000,0.000000,0.000000,NaN,7.910400,NaN,NaN
50%,446.000000,0.000000,3.000000,NaN,NaN,28.000000,0.000000,0.000000,NaN,14.454200,NaN,NaN
75%,668.500000,1.000000,3.000000,NaN,NaN,38.000000,1.000000,0.000000,NaN,31.000000,NaN,NaN
max,891.000000,1.000000,3.000000,NaN,NaN,80.000000,8.000000,6.000000,NaN,512.329200,NaN,NaN

# 판다스 데이터 프레임에서 일부 자료만 추출하기

* 데이터 프레임에서 1개 컬럼만 가져오기

In [82]:
print(df['Name'], type(df['Name'])) 
print(df['Name'].shape, df['Name'].ndim)

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object <class 'pandas.core.series.Series'>
(891,) 1

In [85]:
display(df[['Name']])
print(type(df[['Name']]), df[['Name']].ndim, df[['Name']].shape)

                                                  Name
0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
..                                                 ...
886                              Montvila, Rev. Juozas
887                       Graham, Miss. Margaret Edith
888           Johnston, Miss. Catherine Helen "Carrie"
889                              Behr, Mr. Karl Howell
890                                Dooley, Mr. Patrick

[891 rows x 1 columns]

<class 'pandas.core.frame.DataFrame'> 2 (891, 1)

* 2개 이상 컬럼을 가져오기

In [86]:
df[['Age', 'Name']]

      Age                                               Name
0    22.0                            Braund, Mr. Owen Harris
1    38.0  Cumings, Mrs. John Bradley (Florence Briggs Th...
2    26.0                             Heikkinen, Miss. Laina
3    35.0       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4    35.0                           Allen, Mr. William Henry
..    ...                                                ...
886  27.0                              Montvila, Rev. Juozas
887  19.0                       Graham, Miss. Margaret Edith
888   NaN           Johnston, Miss. Catherine Helen "Carrie"
889  26.0                              Behr, Mr. Karl Howell
890  32.0                                Dooley, Mr. Patrick

[891 rows x 2 columns]

In [87]:
df[['Age', 'Name', 'Cabin']]

      Age                                               Name Cabin
0    22.0                            Braund, Mr. Owen Harris   NaN
1    38.0  Cumings, Mrs. John Bradley (Florence Briggs Th...   C85
2    26.0                             Heikkinen, Miss. Laina   NaN
3    35.0       Futrelle, Mrs. Jacques Heath (Lily May Peel)  C123
4    35.0                           Allen, Mr. William Henry   NaN
..    ...                                                ...   ...
886  27.0                              Montvila, Rev. Juozas   NaN
887  19.0                       Graham, Miss. Margaret Edith   B42
888   NaN           Johnston, Miss. Catherine Helen "Carrie"   NaN
889  26.0                              Behr, Mr. Karl Howell  C148
890  32.0                                Dooley, Mr. Patrick   NaN

[891 rows x 3 columns]

In [88]:
df[['Cabin', 'Age', 'Name']]

    Cabin   Age                                               Name
0     NaN  22.0                            Braund, Mr. Owen Harris
1     C85  38.0  Cumings, Mrs. John Bradley (Florence Briggs Th...
2     NaN  26.0                             Heikkinen, Miss. Laina
3    C123  35.0       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4     NaN  35.0                           Allen, Mr. William Henry
..    ...   ...                                                ...
886   NaN  27.0                              Montvila, Rev. Juozas
887   B42  19.0                       Graham, Miss. Margaret Edith
888   NaN   NaN           Johnston, Miss. Catherine Helen "Carrie"
889  C148  26.0                              Behr, Mr. Karl Howell
890   NaN  32.0                                Dooley, Mr. Patrick

[891 rows x 3 columns]

# 컬럼명 출력하기: .columns

In [95]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

# 데이터 프레임에서 일부 컬럼만 가져오기2
* loc: 인덱스 이름과 컬럼명으로 데이터의 일부를 추출해 가져옴.
```python
df.loc[시작row인덱스이름:끝row인덱스이름, ['컬럼명1', '컬럼명2']]
```
* iloc: 인덱스 번호를 이용해 슬라이싱으로 데이터의 일부를 가져옴
```python
df.iloc[시작row인덱스번호 : 끝row인덱스번호+1, 시작column인덱스번호 : 끝column인덱스번호+1]
```

In [96]:
df[['Name', 'Age']]

                                                  Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
886                              Montvila, Rev. Juozas  27.0
887                       Graham, Miss. Margaret Edith  19.0
888           Johnston, Miss. Catherine Helen "Carrie"   NaN
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[891 rows x 2 columns]

* 이름과 나이 컬럼에서 인덱스 100-150번까지만 가져오고 싶을 때

In [98]:
df.loc[100:150, ['Name', 'Age']]

                                                  Name   Age
100                            Petranec, Miss. Matilda  28.0
101                   Petroff, Mr. Pastcho ("Pentcho")   NaN
102                          White, Mr. Richard Frasar  21.0
103                         Johansson, Mr. Gustaf Joel  33.0
104                     Gustafsson, Mr. Anders Vilhelm  37.0
105                              Mionoff, Mr. Stoytcho  28.0
106                   Salkjelsvik, Miss. Anna Kristine  21.0
107                             Moss, Mr. Albert Johan   NaN
108                                    Rekic, Mr. Tido  38.0
109                                Moran, Miss. Bertha   NaN
110                     Porter, Mr. Walter Chamberlain  47.0
111                               Zabour, Miss. Hileni  14.5
112                             Barton, Mr. David John  22.0
113                            Jussila, Miss. Katriina  20.0
114                              Attalah, Miss. Malake  17.0
115                              Pekoniemi, Mr. Edvard  21.0
116                               Connors, Mr. Patrick  70.5
117                    Turpin, Mr. William John Robert  29.0
118                           Baxter, Mr. Quigg Edmond  24.0
119                  Andersson, Miss. Ellis Anna Maria   2.0
120                        Hickman, Mr. Stanley George  21.0
121                         Moore, Mr. Leonard Charles   NaN
122                               Nasser, Mr. Nicholas  32.5
123                                Webber, Miss. Susan  32.5
124                        White, Mr. Percival Wayland  54.0
125                       Nicola-Yarred, Master. Elias  12.0
126                                McMahon, Mr. Martin   NaN
127                          Madsen, Mr. Fridtjof Arne  24.0
128                                  Peter, Miss. Anna   NaN
129                                 Ekstrom, Mr. Johan  45.0
130                               Drazenoic, Mr. Jozef  33.0
131                     Coelho, Mr. Domingos Fernandeo  20.0
132     Robins, Mrs. Alexander A (Grace Charity Laury)  47.0
133      Weisz, Mrs. Leopold (Mathilde Francoise Pede)  29.0
134                     Sobey, Mr. Samuel James Hayden  25.0
135                                 Richard, Mr. Emile  23.0
136                       Newsom, Miss. Helen Monypeny  19.0
137                        Futrelle, Mr. Jacques Heath  37.0
138                                Osen, Mr. Olaf Elon  16.0
139                                 Giglio, Mr. Victor  24.0
140                      Boulos, Mrs. Joseph (Sultana)   NaN
141                           Nysten, Miss. Anna Sofia  22.0
142  Hakkarainen, Mrs. Pekka Pietari (Elin Matilda ...  24.0
143                                Burke, Mr. Jeremiah  19.0
144                         Andrew, Mr. Edgardo Samuel  18.0
145                       Nicholls, Mr. Joseph Charles  19.0
146       Andersson, Mr. August Edvard ("Wennerstrom")  27.0
147                   Ford, Miss. Robina Maggie "Ruby"   9.0
148           Navratil, Mr. Michel ("Louis M Hoffman")  36.5
149                  Byles, Rev. Thomas Roussel Davids  42.0
150                         Bateman, Rev. Robert James  51.0

In [99]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [113]:
df.iloc[100:151, ::2]

     PassengerId  Pclass     Sex  SibSp              Ticket    Cabin
100          101       3  female      0              349245      NaN
101          102       3    male      0              349215      NaN
102          103       1    male      0               35281      D26
103          104       3    male      0                7540      NaN
104          105       3    male      2             3101276      NaN
105          106       3    male      0              349207      NaN
106          107       3  female      0              343120      NaN
107          108       3    male      0              312991      NaN
108          109       3    male      0              349249      NaN
109          110       3  female      1              371110      NaN
110          111       1    male      0              110465     C110
111          112       3  female      1                2665      NaN
112          113       3    male      0              324669      NaN
113          114       3  female      1                4136      NaN
114          115       3  female      0                2627      NaN
115          116       3    male      0   STON/O 2. 3101294      NaN
116          117       3    male      0              370369      NaN
117          118       2    male      1               11668      NaN
118          119       1    male      0            PC 17558  B58 B60
119          120       3  female      4              347082      NaN
120          121       2    male      2        S.O.C. 14879      NaN
121          122       3    male      0           A4. 54510      NaN
122          123       2    male      1              237736      NaN
123          124       2  female      0               27267     E101
124          125       1    male      0               35281      D26
125          126       3    male      1                2651      NaN
126          127       3    male      0              370372      NaN
127          128       3    male      0             C 17369      NaN
128          129       3  female      1                2668    F E69
129          130       3    male      0              347061      NaN
130          131       3    male      0              349241      NaN
131          132       3    male      0  SOTON/O.Q. 3101307      NaN
132          133       3  female      1           A/5. 3337      NaN
133          134       2  female      1              228414      NaN
134          135       2    male      0          C.A. 29178      NaN
135          136       2    male      0       SC/PARIS 2133      NaN
136          137       1  female      0               11752      D47
137          138       1    male      1              113803     C123
138          139       3    male      0                7534      NaN
139          140       1    male      0            PC 17593      B86
140          141       3  female      0                2678      NaN
141          142       3  female      0              347081      NaN
142          143       3  female      1    STON/O2. 3101279      NaN
143          144       3    male      0              365222      NaN
144          145       2    male      0              231945      NaN
145          146       2    male      1          C.A. 33112      NaN
146          147       3    male      0              350043      NaN
147          148       3  female      2          W./C. 6608      NaN
148          149       2    male      0              230080       F2
149          150       2    male      0              244310      NaN
150          151       2    male      0         S.O.P. 1166      NaN