In [1]:
import joblib
import pandas as pd

In [2]:
test = pd.read_csv("./data/titanic_test.csv")
test

     Survived  Pclass     Sex   Age  SibSp  Parch Embarked
0           0       3    male  24.0      2      0        S
1           0       3    male  44.0      0      1        S
2           1       3    male  22.0      0      0        C
3           0       3    male  41.0      2      0        S
4           1       3  female   NaN      1      0        Q
..        ...     ...     ...   ...    ...    ...      ...
174         1       2  female  25.0      0      1        S
175         0       3    male  20.0      0      0        S
176         0       2    male  28.0      0      0        S
177         1       2  female  23.0      0      0        C
178         0       2    male  31.0      1      1        S

[179 rows x 7 columns]

In [3]:
test['family'] = test['SibSp'] + test['Parch']
test = test.drop(['SibSp','Parch'], axis=1)
test

     Survived  Pclass     Sex   Age Embarked  family
0           0       3    male  24.0        S       2
1           0       3    male  44.0        S       1
2           1       3    male  22.0        C       0
3           0       3    male  41.0        S       2
4           1       3  female   NaN        Q       1
..        ...     ...     ...   ...      ...     ...
174         1       2  female  25.0        S       1
175         0       3    male  20.0        S       0
176         0       2    male  28.0        S       0
177         1       2  female  23.0        C       0
178         0       2    male  31.0        S       2

[179 rows x 6 columns]

In [4]:
X_test = test.drop("Survived", axis=1)
y_test = test["Survived"]

In [5]:
X_test

     Pclass     Sex   Age Embarked  family
0         3    male  24.0        S       2
1         3    male  44.0        S       1
2         3    male  22.0        C       0
3         3    male  41.0        S       2
4         3  female   NaN        Q       1
..      ...     ...   ...      ...     ...
174       2  female  25.0        S       1
175       3    male  20.0        S       0
176       2    male  28.0        S       0
177       2  female  23.0        C       0
178       2    male  31.0        S       2

[179 rows x 5 columns]

In [6]:
y_test

0      0
1      0
2      1
3      0
4      1
      ..
174    1
175    0
176    0
177    1
178    0
Name: Survived, Length: 179, dtype: int64

# 모델 불러와서 예측하기

In [7]:
model = joblib.load("./data/titanic_best_model.joblib")
print(model)

FileNotFoundError: [Errno 2] No such file or directory: './data/titanic_best_model.joblib'

In [ ]:
from sklearn.metrics import classification_report, roc_auc_score

In [ ]:
pred = model.predict(X_test)
print(roc_auc_score(y_test, pred))
print(classification_report(y_test, pred))