In [1]:
# 1

import pandas as pd
print(pd.__version__)

2.3.3

In [2]:
# 2

data = [10, 20, 30, 40, 50]
s = pd.Series(data)
print(s)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [3]:
# 3

s.tolist()

[10, 20, 30, 40, 50]

In [4]:
# 4

a = pd.Series([1, 2, 3, 4])
b = pd.Series([5, 6, 7, 8]) 

print(a+b)
print(a-b)
print(a*b)
print(a/b)

0     6
1     8
2    10
3    12
dtype: int64
0   -4
1   -4
2   -4
3   -4
dtype: int64
0     5
1    12
2    21
3    32
dtype: int64
0    0.200000
1    0.333333
2    0.428571
3    0.500000
dtype: float64

In [5]:
# 5

d = {'a': 100, 'b': 200, 'c': 300, 'd': 400}
s2 = pd.Series(d)
print(s2)

a    100
b    200
c    300
d    400
dtype: int64

In [6]:
# 6

import numpy as np
arr = np.array([10, 20, 30])
s3 = pd.Series(arr)
print(s3)

0    10
1    20
2    30
dtype: int64

In [7]:
# 7

s = pd.Series(['100', '200', 'python', '300.12', '400'])
pd.to_numeric(s, errors='coerce')
print(s)

0       100
1       200
2    python
3    300.12
4       400
dtype: object

In [8]:
# 8

data = {'col1': [1, 2], 'col2': [3, 4]}
df = pd.DataFrame(data)
print(df)

   col1  col2
0     1     3
1     2     4

In [9]:
# 9

s_name = pd.Series(['Amy', 'Bob', 'Chris'])
s_age = pd.Series([25, 30, 22])

df_info = pd.DataFrame({"Name":s_name, "Age":s_age})
print(df_info)

    Name  Age
0    Amy   25
1    Bob   30
2  Chris   22

In [10]:
# 10

df_info.index = ['id_1','id_2','id_3']
df_info

       Name  Age
id_1    Amy   25
id_2    Bob   30
id_3  Chris   22

In [11]:
# 11

arr2d = np.array([[1, 2, 3], [4, 5, 6]])
df_num = pd.DataFrame(arr2d, columns = ['A', 'B', 'C'])
print(df_num)

   A  B  C
0  1  2  3
1  4  5  6

In [12]:
# 12

data_list = [{'name': 'John', 'age': 25}, {'name': 'Jane', 'age': 30}]
df_list = pd.DataFrame(data_list)
print(df_list)

   name  age
0  John   25
1  Jane   30

In [13]:
# 13

dates = pd.date_range('2023-01-01', periods=6)
dates

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06'],
              dtype='datetime64[ns]', freq='D')

In [14]:
# 14

df_dates = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=['A', 'B', 'C', 'D'])
print(df_dates)

                   A         B         C         D
2023-01-01  0.510443  1.743120  0.574646 -1.498073
2023-01-02  1.712893  1.575237  0.156325  0.019991
2023-01-03  1.646080  0.932933 -0.401233  0.942104
2023-01-04 -2.114449 -2.216250 -1.822165  1.870840
2023-01-05  0.592939  1.295074  0.252291  0.178043
2023-01-06 -0.352091  0.304895 -2.236215 -1.287671

In [15]:
# 15

df_dates.head(3)

                   A         B         C         D
2023-01-01  0.510443  1.743120  0.574646 -1.498073
2023-01-02  1.712893  1.575237  0.156325  0.019991
2023-01-03  1.646080  0.932933 -0.401233  0.942104

In [16]:
# 16

print(df_dates.index)
print(df_dates.columns)

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06'],
              dtype='datetime64[ns]', freq='D')
Index(['A', 'B', 'C', 'D'], dtype='object')

In [17]:
# 17

df_dates.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.332636  0.605835 -0.579392  0.037539
std    1.427354  1.474444  1.173548  1.289463
min   -2.114449 -2.216250 -2.236215 -1.498073
25%   -0.136457  0.461904 -1.466932 -0.960756
50%    0.551691  1.114003 -0.122454  0.099017
75%    1.382795  1.505196  0.228300  0.751089
max    1.712893  1.743120  0.574646  1.870840

In [18]:
# 18

print(df_dates.sort_values(by='B', ascending=False))

                   A         B         C         D
2023-01-01  0.510443  1.743120  0.574646 -1.498073
2023-01-02  1.712893  1.575237  0.156325  0.019991
2023-01-05  0.592939  1.295074  0.252291  0.178043
2023-01-03  1.646080  0.932933 -0.401233  0.942104
2023-01-06 -0.352091  0.304895 -2.236215 -1.287671
2023-01-04 -2.114449 -2.216250 -1.822165  1.870840

In [19]:
# 19

df_dates['A']

2023-01-01    0.510443
2023-01-02    1.712893
2023-01-03    1.646080
2023-01-04   -2.114449
2023-01-05    0.592939
2023-01-06   -0.352091
Freq: D, Name: A, dtype: float64

In [20]:
# 20

df_dates[0:3]

                   A         B         C         D
2023-01-01  0.510443  1.743120  0.574646 -1.498073
2023-01-02  1.712893  1.575237  0.156325  0.019991
2023-01-03  1.646080  0.932933 -0.401233  0.942104

In [21]:
# 21

df_dates['2023-01-02':'2023-01-04']

                   A         B         C         D
2023-01-02  1.712893  1.575237  0.156325  0.019991
2023-01-03  1.646080  0.932933 -0.401233  0.942104
2023-01-04 -2.114449 -2.216250 -1.822165  1.870840

In [22]:
# 22

df_dates.loc[dates[0]]

A    0.510443
B    1.743120
C    0.574646
D   -1.498073
Name: 2023-01-01 00:00:00, dtype: float64

In [23]:
# 23

df_dates.loc[:,['A', 'B']]

                   A         B
2023-01-01  0.510443  1.743120
2023-01-02  1.712893  1.575237
2023-01-03  1.646080  0.932933
2023-01-04 -2.114449 -2.216250
2023-01-05  0.592939  1.295074
2023-01-06 -0.352091  0.304895

In [24]:
# 24

df_dates.iloc[3]

A   -2.114449
B   -2.216250
C   -1.822165
D    1.870840
Name: 2023-01-04 00:00:00, dtype: float64

In [25]:
# 25

df_dates.iloc[3:5, 0:1]

                   A
2023-01-04 -2.114449
2023-01-05  0.592939

In [26]:
# 26

df_dates[df_dates['A'] > 0]

                   A         B         C         D
2023-01-01  0.510443  1.743120  0.574646 -1.498073
2023-01-02  1.712893  1.575237  0.156325  0.019991
2023-01-03  1.646080  0.932933 -0.401233  0.942104
2023-01-05  0.592939  1.295074  0.252291  0.178043

In [27]:
# 27

df_dates[df_dates > 0]

                   A         B         C         D
2023-01-01  0.510443  1.743120  0.574646       NaN
2023-01-02  1.712893  1.575237  0.156325  0.019991
2023-01-03  1.646080  0.932933       NaN  0.942104
2023-01-04       NaN       NaN       NaN  1.870840
2023-01-05  0.592939  1.295074  0.252291  0.178043
2023-01-06       NaN  0.304895       NaN       NaN

In [28]:
# 28

# df_dates['E'] = ['one', 'one', 'two', 'three', 'four', 'three']
df_dates

                   A         B         C         D
2023-01-01  0.510443  1.743120  0.574646 -1.498073
2023-01-02  1.712893  1.575237  0.156325  0.019991
2023-01-03  1.646080  0.932933 -0.401233  0.942104
2023-01-04 -2.114449 -2.216250 -1.822165  1.870840
2023-01-05  0.592939  1.295074  0.252291  0.178043
2023-01-06 -0.352091  0.304895 -2.236215 -1.287671

In [29]:
# 29

# print(df_dates[df_dates['E'].isin(['two','four'])])

In [30]:
# 30

df_dates.iloc[0,0] = 100
print(df_dates)

                     A         B         C         D
2023-01-01  100.000000  1.743120  0.574646 -1.498073
2023-01-02    1.712893  1.575237  0.156325  0.019991
2023-01-03    1.646080  0.932933 -0.401233  0.942104
2023-01-04   -2.114449 -2.216250 -1.822165  1.870840
2023-01-05    0.592939  1.295074  0.252291  0.178043
2023-01-06   -0.352091  0.304895 -2.236215 -1.287671

In [31]:
# 31

df_dates.iloc[4,1] = np.nan
print(df_dates.dropna(how='any'))

                     A         B         C         D
2023-01-01  100.000000  1.743120  0.574646 -1.498073
2023-01-02    1.712893  1.575237  0.156325  0.019991
2023-01-03    1.646080  0.932933 -0.401233  0.942104
2023-01-04   -2.114449 -2.216250 -1.822165  1.870840
2023-01-06   -0.352091  0.304895 -2.236215 -1.287671

In [32]:
# 32

print(df_dates.fillna(0))

                     A         B         C         D
2023-01-01  100.000000  1.743120  0.574646 -1.498073
2023-01-02    1.712893  1.575237  0.156325  0.019991
2023-01-03    1.646080  0.932933 -0.401233  0.942104
2023-01-04   -2.114449 -2.216250 -1.822165  1.870840
2023-01-05    0.592939  0.000000  0.252291  0.178043
2023-01-06   -0.352091  0.304895 -2.236215 -1.287671

In [33]:
# 33

print(df_dates.mean())

A    16.914229
B     0.467987
C    -0.579392
D     0.037539
dtype: float64

In [35]:
# 34

df_dates.mean(axis=1)

2023-01-01    25.204923
2023-01-02     0.866111
2023-01-03     0.779971
2023-01-04    -1.070506
2023-01-05     0.341091
2023-01-06    -0.892771
Freq: D, dtype: float64

In [36]:
# 35

df_dates.apply(np.cumsum)

                     A         B         C         D
2023-01-01  100.000000  1.743120  0.574646 -1.498073
2023-01-02  101.712893  3.318357  0.730971 -1.478082
2023-01-03  103.358973  4.251289  0.329739 -0.535978
2023-01-04  101.244524  2.035039 -1.492426  1.334862
2023-01-05  101.837463       NaN -1.240135  1.512905
2023-01-06  101.485372  2.339934 -3.476350  0.225234

In [47]:
# 36

data = {'key': ['A', 'B', 'C', 'A', 'B', 'C'], 'data': range(6)}
df_key = pd.DataFrame(data)
print(df_key.groupby('key').sum())

     data
key
A       3
B       5
C       7

In [48]:
# 37

left = pd.DataFrame({'key': ['foo', 'bar'], 'lval': [1, 2]})
right = pd.DataFrame({'key': ['foo', 'bar'], 'rval': [4, 5]}) 

print(pd.merge(left, right, on='key'))

   key  lval  rval
0  foo     1     4
1  bar     2     5

In [53]:
# 38

df_dates.to_csv("./data/foo.csv", index=False)

In [56]:
# 39

df_loaded = pd.read_csv("./data/foo.csv", index_col=0)
print(df_loaded)

                    B         C         D
A
 100.000000  1.743120  0.574646 -1.498073
 1.712893    1.575237  0.156325  0.019991
 1.646080    0.932933 -0.401233  0.942104
-2.114449   -2.216250 -1.822165  1.870840
 0.592939         NaN  0.252291  0.178043
-0.352091    0.304895 -2.236215 -1.287671

In [57]:
# 40

df = pd.DataFrame(np.random.randn(3, 3), columns=['A', 'B', 'C']) 
df.apply()

          A         B         C
0 -3.374911 -1.508548  0.249961
1 -0.053023 -0.138396 -0.283740
2 -0.553282 -0.402194 -0.647572